name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - run: pip install --upgrade pip uv_build
      - run: pip install -e .
      - run: pytest --maxfail=1 --disable-warnings -q
